name: Build Test Application

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        idf_ver:    ["release-v5.1", "release-v5.2", "release-v5.3"]
        idf_target: ["esp32", "esp32s3"]
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Test Application
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        working-directory: test_apps
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          export PEDANTIC_FLAGS="-DIDF_CI_BUILD -Werror -Werror=deprecated-declarations -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
          export EXTRA_CFLAGS="${PEDANTIC_FLAGS} -Wstrict-prototypes"
          export EXTRA_CXXFLAGS="${PEDANTIC_FLAGS}"
          idf.py build
          rm -rf sdkconfig build managed_components dependencies.lock
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.cxx_without_cxx_exceptions;" build
          rm -rf sdkconfig build managed_components dependencies.lock
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.check_none;" build
          rm -rf sdkconfig build managed_components dependencies.lock
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.log_debug;" build
          rm -rf sdkconfig build managed_components dependencies.lock
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.log_none;" build
          rm -rf sdkconfig build managed_components dependencies.lock
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.mem_custom;" build
          rm -rf sdkconfig build managed_components dependencies.lock
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.mem_esp;" build
